name: Windows Cloud PC - Anydesk

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 10080  # 7 dias (público)

    steps:
      - name: Instalar AnyDesk
        shell: cmd
        run: choco install anydesk -y --ignore-checksums

      - name: Configurar acesso autônomo e obter ID
        shell: cmd
        run: |
          net start AnyDesk
          ping -n 6 127.0.0.1 >nul
          echo Definindo senha de acesso autônomo...
          "C:\Program Files (x86)\AnyDesk\AnyDesk.exe" --set-password wrick2532@R2Lr
          ping -n 6 127.0.0.1 >nul
          echo Obtendo ID...
          "C:\Program Files (x86)\AnyDesk\AnyDesk.exe" --get-id > %TEMP%\id.txt 2>&1
          set /p ID=<%TEMP%\id.txt
          echo =========================================
          echo ID DO ANYDESK: %ID%
          echo =========================================

      - name: Manter Sessão Ativa
        shell: cmd
        run: |
          :keep_alive
          echo Keep alive - %date% %time%
          ping -n 61 127.0.0.1 >nul
          goto keep_alive
